### ISSUE TITLE
feature: split up "config" file to .key and config.toml files

### ISSUE THREAD

**Issue by cdxker** [onthreshold/threshold#57]
Currently NodeConfig is a single json object.

This should be split up into `key.json` and `config.toml`. 

Update `NodeConfig` to read from a `key.json` and a `config.toml` file instead.

`key.json` should only contain `dkg_keys` and `key_data`.

`config.yaml` should contain everything else. Starting out with

```yaml
log_level: DEBUG
log_file: log_output.file

allowed_peers:
  - key = "public_key"
    name = "node_1"
```

Make a test with an example config file and ensure that it reads from the file correctly.
